apiVersion: networking.cfargotunnel.com/v1alpha1
kind: ClusterTunnel
metadata:
  name: kinopoisk-tunnel
  namespace: kinopoisk
spec:
  newTunnel:
    name: kinopoisk-tunnel
  size: 2
  image: cloudflare/cloudflared:2023.8.2
  cloudflare:
    email: mdwit0r@gmail.com
    domain: kinopoisk.dev
    secret: cloudflare-secrets
    accountId: 20f5efa8d1c6c7b4369faee9fe46edb0
