apiVersion: networking.cfargotunnel.com/v1alpha1
kind: ClusterTunnel
metadata:
  name: kinopoisk-tunnel
  namespace: kinopoisk
spec:
  newTunnel:
    name: kinopoisk-tunnel
  size: 2
  image: cloudflare/cloudflared:2023.8.2
  cloudflare:
    email: cloudflare-email
    domain: kinopoisk.dev
    secret: cloudflare-secrets
    accountId: cloudflare-id